apiVersion: v1
kind: Pod
metadata:
  name: simple-secret-pod
  labels:
    name: simple-secret-pod
spec:
  containers:
    - name: simple-secret-pod
      image: simple-secret-pod
      ports:
        - containerPort: 8080
      envFrom:
        - secretRef:
            name: secret-creation