apiVersion: v1
kind: Pod
metadata:
  name: service-account-injection
spec:
  containers:
    - name: nginx
      image: nginx:1.12
      ports:
        - containerPort: 80
  serviceAccountName: service-account-creation