apiVersion: v1
kind: Pod
metadata:
  name: sidecar-containers
spec:
  containers:
    - name: simple-webapp
      image: simple-webapp
      ports:
        - containerPort: 8080
  initContainers:
    - name: log-agent
      image: log-agent
      restartPolicy: Always